name: Benchmark Ministere (optional)

on: [push]

jobs:
  bench:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Run benchmark
        run: |
          python3 benchmark_copilote_ministere.py || true
      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-report
          path: benchmark_report.json
